project_id = "mkgcacuhdwpsfkbguddk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.specs-enhancer]
verify_jwt = false

[functions.force-progress-sync]
verify_jwt = false

[functions.cec-comprehensive-scraper]
verify_jwt = false

[functions.ml-poly-embed]
verify_jwt = false

[functions.ml-poly-match]
verify_jwt = false