project_id = "mkgcacuhdwpsfkbguddk"

[functions.update-cec-data]
verify_jwt = false

[functions.cec-scrape]
verify_jwt = false

[functions.cec-panel-scraper]
verify_jwt = false

[functions.cec-battery-scraper]
verify_jwt = false

[functions.force-complete-scrape]
verify_jwt = false