// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdsqvopgibyfvxlufzln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkc3F2b3BnaWJ5ZnZ4bHVmemxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjM2NTIsImV4cCI6MjA3MTY5OTY1Mn0.soy4nf_cBAHoiGe8a2K0tEylcD5JXs8dPy5uyr9vzBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});