name: Backend CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          cd ml-svc
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd ml-svc
          python -m pytest tests/ -v
          
      - name: Check code formatting
        run: |
          cd ml-svc
          python -m black --check .